global using Microsoft.Azure.Functions.Worker;
global using Microsoft.Extensions.Azure;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Ardalis.Result;
global using MediatR;
global using File.Service.Logs;